### PR TITLE
Nguyen/47 upgrade

### PR DESCRIPTION
**Pull request by expertdicer**
This PR includes:
- Fix checkSpamSubmitProposalMsg
- Using AppKeeper in App and modules
- Using storetypes and exporttypes
- Add Consensus keeper and fixes
- Using simtestutil, simcli,...
- Using storetypes

### CODE REVIEW

**Comment by expertdicer** [comment]
@faddat jacob
Can you pls review my code ? Thank you <3

**Comment by faddat** [comment]
Can you please fix the merge conflicts?

**Comment by faddat** [comment]
Hey, so:

* exportedtypes should be referred to as ibcexported
* few other things, too, that I'll walk through after finishing the merge

**Comment by expertdicer** [comment]
Yes.I think we should get rid of AppKeeper too, as it is not standard.

**Comment by faddat** [comment]
fyi, I am going to merge @Reecepbcups work on v15 into this.

**Comment by expertdicer** [comment]
Yes please. Thank you

**Comment by Reecepbcups** [comment]
Closed per comment in the PR 646 branch I worked on. I did review this and there are multiple sections of incorrect behavior / setup still excluding the testing areas (since we have 5 of those)

**Pull request closed without merging**
