### PR TITLE
E2E

### PR DESCRIPTION
**Pull request by vuong177**
## What is the purpose of the change

 Add End to end tests for Juno.
 The e2e package defines an integration testing suite used for full end-to-end testing functionality.
 It initializes the chains for testing via Docker.
### Features included in this PR
1. Basic logic

* This is the most basic type of setup where a single chain is created
* It simply spins up the desired number of validators on a chain.
3. Test IBC Token Transfer
* Ibc transfer test
* Using Hermes Relayer
4. Test Token Factory Bindings
* TokenFactory module and its bindings work as expected
5. Upgrade testing
* CLI commands are run to create an upgrade proposal and approve it
* Old version containers are stopped and the upgrade binary is added
* Current branch Juno version is spun up to continue with testing
### Features will do in future

 - State Sync Testing
 - TestTWAP
 - Test Global Fee

### CODE REVIEW

**Comment by vuong177** [comment]
This failed because of we don't have v11-init-chain image. Automate workflows to create it will run when we merge this PR into main.

**Comment by faddat** [comment]
ok so this is blocked by:

* https://github.com/CosmosContracts/juno/issues/371

?

**Comment by vuong177** [comment]
@faddat yep

**Comment by faddat** [comment]
Let's slate this for v13 then, no worries :)

**Comment by vuong177** [comment]
I prefer using old log. Easier for debug.

**Comment by JakeHartnell** [comment]
Is this still blocked?

**Comment by faddat** [comment]
@JakeHartnell it never really was, Jack had wanted to use ibctest.  I defer to @vuong177 and @Reecepbcups as to weather that is the right path.  I need to watch the ibctest presentation.

**Comment by vuong177** [comment]
I think we should merge this PR first. We can integrate with IBC-test by future PRs. By #371 has been merged, this PR is ready to merge.

**Comment by faddat** [comment]
Thanks vuong!  I am going to defer to others, on this, but will enable auto-merge.

**Comment by faddat** [comment]
This branch should add some attribution to gaia/osmosis.

**Comment by vuong177** [comment]
Will add a README.md about this.

**Comment by anhductn2001** [comment]
I think this PR can be merged ASAP. It's working pretty well now with some test ( like Chain-upgrade, IBC transfer ). I know we are planning` ibc-test `integration but we can use e2e first in this time

**Comment by faddat** [comment]
I've removed the TODO and am adding an issue, goal should be to keep statik out of our code, and use embed to serve the OpenAPI UI, which is very nice.

**Comment by faddat** [comment]
https://github.com/CosmosContracts/juno/issues/400

**Review by catShaark — APPROVED** [review]

**Pull request merged**
