### PR TITLE
test: introduce interchaintest as an e2e testing framework

### PR DESCRIPTION
**Pull request by jtieri**
This PR introduces `interchaintest` as the e2e testing framework for Juno.

There are two testing cases included here. A basic test for testing that spinning up Juno works and another test that spins up Juno and Gaia before creating all of the on chain artifacts for IBC and sending some ICS-20 transfer packets between the two chains.

You will notice a `chains.yaml` file, this is utilized by [Heighliner](https://github.com/strangelove-ventures/heighliner) which is a tool Strangelove has built for easily building Docker images for blockchains across the Interchain. This can be helpful when iterating on test cases locally.

There are a few additional Makefile cmds I have added.
- `ictest-basic` will execute the basic tests
- `ictest-ibc` will execute the IBC related tests
- `get-heighliner` will clone the [heighliner](https://github.com/strangelove-ventures/heighliner) repo 
- `local-image` will use heighliner to build a local Docker image for testing purposes

I have added a GitHub workflow which will build a Docker image from the working branch upon each push and run the `interchaintest` test cases. This integrates `interchaintest` into Juno's CI/CD pipeline.

### CODE REVIEW

**Comment by Reecepbcups** [comment]
This branch will fail due to the current e2e solution most likely - so I'll review and get this merged in later today once it looks good :D 

I briefly skimmed but did not see: is there an upgrade test? So upgrade from our repo's 13.0.0 to latest branch? If not I can probably throw in after merge

**Comment by jtieri** [comment]
> This branch will fail due to the current e2e solution most likely I'll review and get this merged in later today once it looks good :D
> 
> I briefly skimmed but did not see: is there an upgrade test? So upgrade from our repo's 13.0.0 to latest branch? If not I can probably throw in after merge

Ahh I somehow missed that one when we were chatting earlier!

I could bring that in now or get a follow up PR opened after this is merged since this is already ~2k changes.

It should be relatively straightforward since we already have this implemented in the `interchaintest` repo, so it's really just porting the code over here see: https://github.com/strangelove-ventures/interchaintest/blob/main/examples/cosmos/chain_upgrade_test.go

**Comment by Reecepbcups** [comment]
@jtieri You can bring it in now, especially since this is the start of the v14 branch. Important the upgrades are good

Thankfully review process should be pretty quick despite # of lines :)

**Comment by jtieri** [comment]
Sounds good to me! Getting close to my EOD so if I don't have it done today I will wrap things up tomorrow!

**Comment by Reecepbcups** [comment]
Reviewed, ran, and looks good to me - please tag me tomorrow after the upgrade test is added. Thank you again! Really appreciate this

**Comment by faddat** [comment]
seconded!

**Comment by faddat** [comment]
Reece I was going to merge but want to hold off since it's your personal branch.  Looks good tho!

**Comment by jtieri** [comment]
Alright chain upgrade test is included now, this should upgrade from v13 using the docker image built on CI runs. @Reecepbcups

**Pull request merged**
