### PR TITLE
Reinstate dockerfile

### PR DESCRIPTION
**Pull request by the-frey**
I think we probably jumped the gun on ripping this all out and want to restore it ASAP.

Will probably need a few tries to get everything working again.

### CODE REVIEW

**Review by JakeHartnell — APPROVED** [review]
LGTM

**Comment by the-frey** [comment]
This supercedes #175

**Review by JakeHartnell — APPROVED** [review]

**Comment by the-frey** [comment]
Will want to get this merged off the bat but observe that this means we can now do ARM builds and that I should document how to do so when our hair is not on fire (pass a flag to compose/pass the build-arg to the main container).

**Review by dimiandre — APPROVED** [review]
LFG

**Review by giansalex — APPROVED** [review]

**Pull request merged**
