### PR TITLE
Enable codacy

### PR DESCRIPTION
**Pull request by faddat**
This PR runs a suite of lint and security checks

### CODE REVIEW

**Review by JakeHartnell — APPROVED** [review]
LGTM

**Comment by Reecepbcups** [comment]
Personally not a fan of this / these checks, especially when it comes to bash. This is why we denied it last time (myself & Alex). There comes a limit to where more linting is more of a headache for little to no return.

**Comment by faddat** [comment]
So, this or some secondary linter, will improve our openssf score.

**Comment by Reecepbcups** [comment]
yea, I'm still against per our previous comments https://github.com/CosmosContracts/juno/pull/508. Juno needs more development, not cleaning up things. Code base is in good standing with standard golint on 1.52

**Comment by faddat** [comment]
The other thing that I can do with this, is maybe implement some of the constituient pieces of codacy, without using the whole gigantic thing.

**Comment by faddat** [comment]
yeah, personally I think clean and build go hand in hand.  LMK if there's anything you'd like a hand building.

**Comment by faddat** [comment]
given a 3rd negative experience -- lets kaboomie this

**Pull request closed without merging**
