### PR TITLE
Revert "Remove custom /txs endpoint"

### PR DESCRIPTION
**Pull request by the-frey**
I don't think it's what crashed the chain but Keplr is no longer working for sends on my local machine and think this is the culprit. Maybe?

Reverts CosmosContracts/juno#147

### CODE REVIEW

**Comment by giansalex** [comment]
@the-frey did you add the "no-legacy-stdTx" feature?

**Comment by giansalex** [comment]
works with [these features](https://github.com/giansalex/juno-cw20/blob/24cee0cb316cd54f65eac7c47bc272a771f71cd3/src/main.js#L228)

**Comment by the-frey** [comment]
Right, but should we be telling all app devs to update? Seems poor form to just break their stuff. Might be better to work out a smoother upgrade path. Thoughts @JakeHartnell ?

**Comment by giansalex** [comment]
since Juno is natively on keplr, this will not happen on mainnet.
I don't think this should be reverted just for testnet, we can add docs for this, and share the correct configuration for suggest chain in keplr

**Comment by the-frey** [comment]
Yeah, could be persuaded by that approach. A bit annoying for app devs, but not the end of the world. Let's see what Jake's take is...

**Comment by the-frey** [comment]
@JakeHartnell / @dimiandre what do you think for this? It looks like app devs will have to add a bit of extra config for keplr to work.

**Comment by the-frey** [comment]
Ah yeah I guess we're on 45+ anyway

**Comment by the-frey** [comment]
@giansalex getting reports that this is broken on local and `no-legacy-stdTx` feature does not fix it. Do you know of another workaround? Otherwise going to re-open and move to revert this.

**Comment by giansalex** [comment]
first we should know what the error is.  
maybe it is related to the wasm REST change, and reverting this will not fix it.
i will ask in discord for more details

**Comment by the-frey** [comment]
I'm now beginning to think it's actually that the REST server isn't enabled. I'm going to add it to the dev config for Juno as a flag, and then see if turning that on solves it 🤔

**Comment by giansalex** [comment]
ok, anyway I have asked in discord, if they give more details.

**Comment by the-frey** [comment]
I've put a PR in that enables the REST server if you set the CORS flag for local dev. That seems to fix the problem for local chains, so I reckon that's the quickest fix for local development.

**Pull request closed without merging**
