### PR TITLE
[v15] Pull in x/tokenfactory + interchain binding & Tx test

### PR DESCRIPTION
**Pull request by Reecepbcups**
# Features
- Pulls in the tokenfactory proto & module from our fork
- Moves interchain test from test/interchaintest to just interchaintest
- Writes a Binding + Tx tokenfactory interchain e2e test

# Main module import changes
- x/tokenfactory/**.go *(copy paste of from our token-factory fork + capabilities)*

# Other files of importance
- interchaintest/tokenfactory_test.go
- .github/workflows/interchaintest-E2E.yml
- interchaintest/helpers/*.go

### CODE REVIEW

**Review by faddat — APPROVED** [review]

**Comment by faddat** [comment]
All right. So my summary here is that you basically change the location of the interchange test tests and you pulled in token factory. To any subsequent reviewer, if I got this wrong, please request changes but I believe that this is what I'm reading here. Thank you.

**Comment by faddat** [comment]
also i love this pr

**Comment by faddat** [comment]
Merging this into the 47 branch so no conflicts later

**Comment by faddat** [comment]
* https://github.com/CosmosContracts/juno/issues/674

**Review by dimiandre — APPROVED** [review]
Looks good!

**Pull request merged**
