### PR TITLE
go workspaces

### PR DESCRIPTION
**Pull request by faddat**
A recent Juno dev meme has been approximately "let's tidy the price feeder!"

But what if we could simply "go work sync" and it would be tidied for us?

Dream no more, go workspaces are here :)

### CODE REVIEW

**Review by JakeHartnell — APPROVED** [review]
Oh nice, didn't know about this feature.

**Comment by faddat** [comment]
This is kinda waiting on these:

* https://github.com/strangelove-ventures/packet-forward-middleware/pull/51
* https://github.com/strangelove-ventures/packet-forward-middleware/pull/70

**Comment by Reecepbcups** [comment]
I'll approve when this works, though I did add "make all" to go mod tidy and lint both

I guess this is the more correct way to do that

**Comment by faddat** [comment]
Yeah it is waiting on some upstream stuff.

**Pull request closed without merging**
