### PR TITLE
[WIP] Add custom mint module

### LINKED ISSUE #27: Inflation module
Need to develop a custom minting/inflation module that fit juno tokenomics details

### PR DESCRIPTION
**Pull request by giansalex**
This include:
- Base module by #33 
- Fix module imports
- Add Proto files (rebuild)
- **Juno tokenomics** impl

close #27 

Test: https://github.com/disperze/Juno/blob/mint-module/x/mint/types/minter_test.go#L12

image

### CODE REVIEW

**Comment by faddat** [comment]
Should I merge yours into mine, 

mine into yours

or one of ours into main then the other?

I finished 0.43.0

....and you did damn fine work on the inflation module.  Interesting!

**Comment by giansalex** [comment]
@faddat i can bring #37 changes after merge.

**Comment by giansalex** [comment]
Proofs

Mint params -> `"blocks_per_year": "50"`
image


Supply fixed after 0 inflation
image


Rewards after 0 inflation
- no txs
image
- some txs
image

**Comment by giansalex** [comment]
Some `mint_params` are not used 
- `inflation_rate_change`
- `inflation_max`
- `inflation_min`
- `goal_bonded`

do i need to remove them?

**Comment by dimiandre** [comment]
> Some `mint_params` are not used
> 
>     * `inflation_rate_change`
> 
>     * `inflation_max`
> 
>     * `inflation_min`
> 
>     * `goal_bonded`
> 
> 
> do i need to remove them?

Yes better to remove. 

Also would be cool to have phases as parameters as well, so we can edit using governance.


Thanks for the good work! Will start reviewing it now.

**Comment by faddat** [comment]
My review is about 24 hours out.  As a preliminary, I just want to say that it looks great!

**Comment by giansalex** [comment]
Tests passed

image

**Comment by faddat** [comment]
on it now....

**Review by faddat — APPROVED** [review]
I approve, but do not think that we should directly merge this.  

Last night I combined it with a 0.43.0 upgrade.  Let me make a PR with that, and that is what I think that we should merge.  

Some changes (which should be reviewed) were needed, and that's why I figure that we shift to that.

wdyt?

Also I formally approved, cause it would be no problem to merge this.  Either way, I suppose.

**Review by JakeHartnell — APPROVED** [review]
Nice and simple. LGTM.

**Comment by faddat** [comment]
lgtm

**Pull request merged**
