### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by faddat**
Get e'm up and running with a node, fast.

### CODE REVIEW

**Comment by the-frey** [comment]
see #20 #19 - as this is related to a testnet, I think it belongs in the testnets repo https://github.com/CosmosContracts/testnets/tree/main/lucina and all three PRs can be combined into one 👍

**Comment by giansalex** [comment]
Its more easy share `rpc` endpoint.

**Comment by giansalex** [comment]
For ease of use, share the rpc endpoint.

**Comment by the-frey** [comment]
Closing as related to other PRs that are now closed.

**Pull request closed without merging**
