### PR TITLE
v16: Integrate Skip's Protocol Owned Builder

### PR DESCRIPTION
**Pull request by keefertaylor**

### CODE REVIEW

**Comment by Reecepbcups** [comment]
This only runs base CI, I dont have ictest working with PullRequest yet. Will confirm in a moment

**Comment by Reecepbcups** [comment]
Running CI on https://github.com/CosmosContracts/juno/tree/reece-pob with some changes to cherry pick here once confirmed good

**Review by Reecepbcups — APPROVED** [review]
LGTM thank you!

**Comment by xlab** [comment]
Hi @Reecepbcups, I am late to the party here, but wanted to notify that we have a working ictest for POB:
https://github.com/persistenceOne/persistenceCore/blob/main/interchaintest/module_pob_test.go

Feel free to borrow, yet I think we will have to improve it, as currently it tests only that the tx included in the auction tx is executed properly.

**Comment by Reecepbcups** [comment]
@xlab Thank you! I will get this in sometime this week. Really appreciate the work you are doing here

Also stoked to see you guys use my design style for test setup! I still need to clean it up and make it more versatile but it's a good start. I may get it up into main branch v7, will see. If you have additions or ideas let me know on [twitter](https://twitter.com/Reecepbcups_) DM :)

**Comment by xlab** [comment]
> Also stoked to see you guys use our design style for test setup

Hehe true, it's very inspiring to see e2e organized so well. One of the major selling points was that the tests can be shared between different chains. And of course I hope this way will become truly canonical, so everyone will focus on tests and not maintaining the boilerplate.

**Pull request merged**
