### PR TITLE
feat(POB): In-Protocol Top of Block Auctions (V1)

### PR DESCRIPTION
**Pull request by davidterpay**
## Overview
This PR integrates Skip's POB V1 into Juno. We are still pending a few changes from the audit so I will make sure to update the release in this PR once it is cut and remove some of the genesis code that is currently required to start up. In terms of testing, there is a script that will be merged into POB soon that will allow the team to verify transactions are executing successfully at the top of block (and are rejected when they should be).

### CODE REVIEW

**Comment by Reecepbcups** [comment]
@davidterpay Do you think you could get this bumped to v1.0.1 & passing CI in the next day or 2? I would like to get v16 up on Uni Thurs/Friday this week.

If now we can bump it back to v17 which is much smaller & will be out in August.

**Comment by keefertaylor** [comment]
Hi @Reecepbcups! 

@davidterpay is on vacation this week, so I'll be taking over this work. Apologies for not seeing your comment on this PR sooner. I'll try to get this done by EOD today, California time. 

LMK if you need it more urgently than that.

**Comment by Reecepbcups** [comment]
@keefertaylor This works for me (EOD today or by tomorrow afternoon)! 

Thank you very much 🙏🏻

**Comment by keefertaylor** [comment]
@Reecepbcups Sorry for the delay. I did some work today, but it's a bit more than I realized.  We'll get this over to you tomorrow.

**Comment by Reecepbcups** [comment]
@keefertaylor All good. Make sure to pull in main if you have not already, all CI confirms passing there + is linted :)

**Comment by Reecepbcups** [comment]
Completed in https://github.com/CosmosContracts/juno/pull/750

**Pull request closed without merging**
