### PR TITLE
Allow IBC on smartcontract

### PR DESCRIPTION
**Pull request by giansalex**
Currently, i get this error:

image

### CODE REVIEW

**Comment by the-frey** [comment]
LGTM. Any objections @JakeHartnell / @dimiandre ?

**Comment by giansalex** [comment]
is it also possible to enable this flag?
https://github.com/CosmosContracts/Juno/blob/c6dde2025e178bba0e41c46cb35dcef6312b7cc0/app/app.go#L101

**Comment by JakeHartnell** [comment]
Oh, we may need to make a proposal to enable IBC via governance. Keep this ticket open.

Can probably change the `ProposalsEnabled` flag.

**Comment by the-frey** [comment]
If I understand @JakeHartnell correctly, that second commit should be on a separate branch...

**Comment by the-frey** [comment]
Just so I understand @JakeHartnell - why would we need governance to enable IBC? A number of Hack Juno challenges seem predicated on it, and Juno is being talked up as being IBC enabled from network launch. It seems that would also include IBC for SCs...?

**Pull request closed without merging**
