### PR TITLE
Change compile cost again

### PR DESCRIPTION
**Pull request by the-frey**
WIP - currently testing locally but want the docker image created by the PR

### CODE REVIEW

**Comment by the-frey** [comment]
Okay, see very long-winded hacking discussed on #117

**Comment by the-frey** [comment]
So locally, with validator gas fees set to `0.025ujunox` 

    TXFLAG="--gas-prices 0.01$DENOM --gas auto --gas-adjustment 1.5 -y -b block --chain-id $CHAIN_ID --node $RPC"

FAILS

    insufficient fees; got: 476050ujunox required: 1190124ujunox: insufficient fee"

Upping fees:

     TXFLAG="--gas-prices 0.1$DENOM --gas auto --gas-adjustment 1.5 -y -b block --chain-id $CHAIN_ID --node $RPC"

Succeeds. The cost to the key for sending is:

'4760494`

**Comment by the-frey** [comment]
TL;DR of options:
1. This ⚖️ 
2. Reduce down to wasmd default (much lower than `100`, which is a 10x of our original bump) 😓 
3. YOLO and keep the 10x version that this lowers (`1000`) with the assumption that we may need a param change on mainnet and might be opening ourselves up to an attack vector 🤷

**Review by faddat — APPROVED** [review]

**Comment by giansalex** [comment]
so revert #117  and back to 100 ...

**Comment by the-frey** [comment]
@giansalex yeah we can do that - we probably want the version bump in the docker container and we _definitely_ want the fees change (means this stuff can be locally tested) - but can put those in a separate PR?

**Review by JakeHartnell — APPROVED** [review]

**Pull request merged**
