### PR TITLE
Add query stargate for token factory

### LINKED ISSUE #457: Use stargate query for token factory.
## Background

- Wasmd v0.30.0 has stargate query, so we do not need wasmbinding for query chain state from smart contract.
- Notional team are building a rust library for stargate here : https://github.com/notional-labs/juno-rust.

## Suggested Design
- Migrate tokenfactory custom query to stargate query
- Write new contract for tokenfactory testing

## Acceptance Criteria
- Have new contract for e2e test
- All test passed

### PR DESCRIPTION
**Pull request by GNaD13**
Closed #457

### CODE REVIEW

**Comment by faddat** [comment]
Hey, this is good stuff!

**Review by vuong177 — COMMENTED** [review]
@GNaD13 we need to write the new tokenfactory contract && rewrite the e2e test for tf module.

**Comment by GNaD13** [comment]
> 

got it

**Review by faddat — DISMISSED** [review]

**Comment by Reecepbcups** [comment]
E2E Error for query - https://github.com/CosmosContracts/juno/actions/runs/3821978351/jobs/6501658332#step:9:1151

**Comment by vuong177** [comment]
Because in this PR we move to use stargate instead of wasmbinding. We need to re-write sample contracts for this.

**Comment by faddat** [comment]
@vuong177 what is needed to get this one over the line?

**Comment by faddat** [comment]
It is over the line. Just adds stargate queries for ye olde TF

**Review by faddat — APPROVED** [review]

**Review by Reecepbcups — APPROVED** [review]
utACK

**Pull request merged**
