### PR TITLE
Integrate ICA Host Functionality

### PR DESCRIPTION
**Pull request by the-frey**
This PR supercedes #215 and seeks to only integrate ICA Host functionality, rather than ICA Controller as well.

### CODE REVIEW

**Comment by the-frey** [comment]
@joeabbey @faddat here's a recut of #215 that only integrates ICA Host for now so we can start to test this on uni and in some automated tests.

**Review by joeabbey — APPROVED** [review]
Compared side-by-side with #215.

Thanks for paring this down to just Host

**Review by faddat — APPROVED** [review]
Like @joeabbey -- I also like how this is just the host, there's a set of odd issues with controller auth.

**Comment by asalzmann** [comment]
Has this been released?

**Pull request merged**
