### PR TITLE
Airdrop command changes

### PR DESCRIPTION
**Pull request by the-frey**
WIP for now, needs more testing

- adds community pool param to `AddAirdropAccounts`
- uses this amount plus a counter of balances to set total supply
- marshals the two above into the output genesis file

### CODE REVIEW

**Comment by the-frey** [comment]
Probably https://github.com/CosmosContracts/Juno/pull/16 is worth getting into the `zaki-airdrop` branch before this one is done as well, as there's likely to be some changes needed.

**Comment by the-frey** [comment]
Now #16 is merged into `zaki-airdrop`, I've merged that up into this working branch and will test building a genesis using the stuff in the `mainnet` repo to see if it fixes #15

**Comment by the-frey** [comment]
Okay, the format of the community pool needs changing, but it's nearly there....

**Comment by the-frey** [comment]
Ok, I think this is actually ready for review now. My only other concern is that I've noticed every account has its `account_number` set to 0 in the genesis, but they're incremented when generated elsewhere. Should we be enforcing uniqueness? I don't fully grok the purpose of that field, hence asking.

**Review by faddat — COMMENTED** [review]
This looks good but will need to test it, as well.  

I think this would be a very useful module in the sdk, too.

**Review by dimiandre — APPROVED** [review]
Lgtm

**Pull request merged**
