### PR TITLE
10x compile cost again

### PR DESCRIPTION
**Pull request by the-frey**
Will drop a note in TG about this.

### CODE REVIEW

**Comment by the-frey** [comment]
local testing: 

set to `500` fails at default gas prices/adj

```
junod tx wasm store ./artifacts/whoami.wasm --from unsafe-test --gas auto -b block --output json --chain-id testing --gas-prices 0.01ustake --gas-adjustment 1.5
```
= 2323646 fees

set to 1000 (same cmd):

= 4633076 fees

**Comment by the-frey** [comment]
@dimiandre @JakeHartnell ☝️

**Comment by JakeHartnell** [comment]
> local testing:
> 
> set to `500` fails at default gas prices/adj
> 
> ```
> junod tx wasm store ./artifacts/whoami.wasm \
>   --from unsafe-test \
>   --gas auto -b block \
>   --output json \
>   --chain-id testing \
>   --gas-prices 0.01ustake \
>   --gas-adjustment 1.5
> ```
> 
> = 2323646 fees (uDENOM)
> 
> set to 1000 (same cmd):
> 
> = 4633076 fees (uDENOM)

Looks about right. :100:

**Comment by the-frey** [comment]
@JakeHartnell which one? 500, or 1k?

**Comment by JakeHartnell** [comment]
> @JakeHartnell which one? 500, or 1k?
> 
> As per the discussion on TG, as this was on my laptop, I'd expect the fees to be higher on a real network with other traffic rolling through thinking
> 
> For ref, on `astarte-1` testnet, with it set to 100, the cost was just under 1JUNOX (about 800kujunox)

I vote higher. :shrug:

**Comment by the-frey** [comment]
1K? punish me with fees, daddy

**Comment by the-frey** [comment]
@dimiandre / @faddat what do you think? (also feel free to test this locally)

**Comment by faddat** [comment]
I fully endorse punishing ourselves and everyone else with fees, daddy.

**Review by JakeHartnell — APPROVED** [review]

**Review by faddat — APPROVED** [review]
Reality:  those super high eth fees actually prove demand.

**Comment by the-frey** [comment]
So this was tested on `astarte-2` - with val set to 1000 it did not seem possible to get a tx through when the per block gas limit set to `100_000_000` as it is on mainnet. When that was increased to `500_000_000` it worked:

```
junod tx wasm store "./artifacts/whoami.wasm" --from needlecast --output json --chain-id astarte-2 --gas-prices 0.1ujunox --gas-adjustment 1.5 --gas auto -b block
```

fee:

    "auth_info":{"signer_infos":[],"fee":{"amount":[{"denom":"ujunox","amount":"46330263"}]


whole log:

```json
{
	"height": "40244",
	"txhash": "83916077AFC949C1CDF37A08585551A15CB6D64E8D62FB7678589431E8DEC00B",
	"codespace": "",
	"code": 0,
	"data": "0A240A1E2F636F736D7761736D2E7761736D2E76312E4D736753746F7265436F646512020801",
	"raw_log": "[{\"events\":[{\"type\":\"message\",\"attributes\":[{\"key\":\"action\",\"value\":\"/cosmwasm.wasm.v1.MsgStoreCode\"},{\"key\":\"module\",\"value\":\"wasm\"},{\"key\":\"sender\",\"value\":\"juno1w8cpaaljwrytquj86kvp9s72lvmddcc2s67c82\"}]},{\"type\":\"store_code\",\"attributes\":[{\"key\":\"code_id\",\"value\":\"1\"}]}]}]",
	"logs": [{
		"msg_index": 0,
		"log": "",
		"events": [{
			"type": "message",
			"attributes": [{
				"key": "action",
				"value": "/cosmwasm.wasm.v1.MsgStoreCode"
			}, {
				"key": "module",
				"value": "wasm"
			}, {
				"key": "sender",
				"value": "juno1w8cpaaljwrytquj86kvp9s72lvmddcc2s67c82"
			}]
		}, {
			"type": "store_code",
			"attributes": [{
				"key": "code_id",
				"value": "1"
			}]
		}]
	}],
	"info": "",
	"gas_wanted": "463302624",
	"gas_used": "308881643",
	"tx": null,
	"timestamp": "",
	"events": [{
		"type": "coin_spent",
		"attributes": [{
			"key": "c3BlbmRlcg==",
			"value": "anVubzF3OGNwYWFsandyeXRxdWo4Nmt2cDlzNzJsdm1kZGNjMnM2N2M4Mg==",
			"index": true
		}, {
			"key": "YW1vdW50",
			"value": "NDYzMzAyNjN1anVub3g=",
			"index": true
		}]
	}, {
		"type": "coin_received",
		"attributes": [{
			"key": "cmVjZWl2ZXI=",
			"value": "anVubzE3eHBmdmFrbTJhbWc5NjJ5bHM2Zjg0ejNrZWxsOGM1bHh0cW12cA==",
			"index": true
		}, {
			"key": "YW1vdW50",
			"value": "NDYzMzAyNjN1anVub3g=",
			"index": true
		}]
	}, {
		"type": "transfer",
		"attributes": [{
			"key": "cmVjaXBpZW50",
			"value": "anVubzE3eHBmdmFrbTJhbWc5NjJ5bHM2Zjg0ejNrZWxsOGM1bHh0cW12cA==",
			"index": true
		}, {
			"key": "c2VuZGVy",
			"value": "anVubzF3OGNwYWFsandyeXRxdWo4Nmt2cDlzNzJsdm1kZGNjMnM2N2M4Mg==",
			"index": true
		}, {
			"key": "YW1vdW50",
			"value": "NDYzMzAyNjN1anVub3g=",
			"index": true
		}]
	}, {
		"type": "message",
		"attributes": [{
			"key": "c2VuZGVy",
			"value": "anVubzF3OGNwYWFsandyeXRxdWo4Nmt2cDlzNzJsdm1kZGNjMnM2N2M4Mg==",
			"index": true
		}]
	}, {
		"type": "tx",
		"attributes": [{
			"key": "ZmVl",
			"value": "NDYzMzAyNjN1anVub3g=",
			"index": true
		}]
	}, {
		"type": "tx",
		"attributes": [{
			"key": "YWNjX3NlcQ==",
			"value": "anVubzF3OGNwYWFsandyeXRxdWo4Nmt2cDlzNzJsdm1kZGNjMnM2N2M4Mi83",
			"index": true
		}]
	}, {
		"type": "tx",
		"attributes": [{
			"key": "c2lnbmF0dXJl",
			"value": "TGVCRmJMaUtKcG9NTEZwWW81SldnNmsvUitXZ0ZPUFJuOEI5QncrWDdIdG1VbERFd1VGemcwZ0F0cE5kOVBZV0lLWGh3MW9UZmNWYU5LT3RGdy9oQlE9PQ==",
			"index": true
		}]
	}, {
		"type": "message",
		"attributes": [{
			"key": "YWN0aW9u",
			"value": "L2Nvc213YXNtLndhc20udjEuTXNnU3RvcmVDb2Rl",
			"index": true
		}]
	}, {
		"type": "message",
		"attributes": [{
			"key": "bW9kdWxl",
			"value": "d2FzbQ==",
			"index": true
		}, {
			"key": "c2VuZGVy",
			"value": "anVubzF3OGNwYWFsandyeXRxdWo4Nmt2cDlzNzJsdm1kZGNjMnM2N2M4Mg==",
			"index": true
		}]
	}, {
		"type": "store_code",
		"attributes": [{
			"key": "Y29kZV9pZA==",
			"value": "MQ==",
			"index": true
		}]
	}]
}
```

**Comment by the-frey** [comment]
Worth noting that with the command that perfectly mirrors dev:

    junod tx wasm store "./artifacts/whoami.wasm" --from needlecast --output json --chain-id astarte-2 --gas-prices 0.01ujunox --gas-adjustment 1.5 --gas auto -b block

Got 

    "fee":{"amount":[{"denom":"ujunox","amount":"4633027"}]

```
{"height":"0","txhash":"B2AA9E07CA8A9C74082503554D421F239682572444B4B1210FA5F2DD16D514F4","codespace":"sdk","code":13,"data":"","raw_log":"insufficient fees; got: 4633027ujunox required: 11582566ujunox: insufficient fee","logs":[],"info":"","gas_wanted":"463302624","gas_used":"3396","tx":null,"timestamp":"","events":[]}
```

**Comment by the-frey** [comment]
So I'm led to conclude that either 100 or 200 will likely work as a value, even with current gas limit. This can be checked on a laptop, I think, so I will do that now.

**Comment by the-frey** [comment]
okay locally, in a docker container with:

    TX Flags: --gas-prices 0.01ujunox --gas auto --gas-adjustment 1.3 -y -b block --chain-id testing --node 

```
Pre-store balance:
balances: - amount: "1000000000" denom: ucosm - amount: "750000000" denom: ujunox pagination: next_key: null total: "0"
```
you get:

    gas estimate: 81287731

```json
{
	"height": "2",
	"txhash": "D23D279C4E57772C53481061C8D928B21D9E4842E57D84DD0C301478212E8C73",
	"codespace": "",
	"code": 0,
	"data": "0A240A1E2F636F736D7761736D2E7761736D2E76312E4D736753746F7265436F646512020801",
	"raw_log": "[{\"events\":[{\"type\":\"message\",\"attributes\":[{\"key\":\"action\",\"value\":\"/cosmwasm.wasm.v1.MsgStoreCode\"},{\"key\":\"module\",\"value\":\"wasm\"},{\"key\":\"sender\",\"value\":\"juno14nxpcfc7c0gqhk49c9c0r6a2v32fxhqh5eg3kx\"}]},{\"type\":\"store_code\",\"attributes\":[{\"key\":\"code_id\",\"value\":\"1\"}]}]}]",
	"logs": [{
		"msg_index": 0,
		"log": "",
		"events": [{
			"type": "message",
			"attributes": [{
				"key": "action",
				"value": "/cosmwasm.wasm.v1.MsgStoreCode"
			}, {
				"key": "module",
				"value": "wasm"
			}, {
				"key": "sender",
				"value": "juno14nxpcfc7c0gqhk49c9c0r6a2v32fxhqh5eg3kx"
			}]
		}, {
			"type": "store_code",
			"attributes": [{
				"key": "code_id",
				"value": "1"
			}]
		}]
	}],
	"info": "",
	"gas_wanted": "81287731",
	"gas_used": "62542149",
	"tx": null,
	"timestamp": "",
	"events": [{

	}]
}
```

balance check shows:

```
Stored:
Post-store balance:
balances: - amount: "1000000000" denom: ucosm - amount: "749187122" denom: ujunox pagination: next_key: null total: "0"
```

Cost was `812878`

**Comment by the-frey** [comment]
With gas set to mainnet value, and compile cost at `1000` we see the same error as on `astarte-2` with the same flags:

```
TX Flags: --gas-prices 0.01ujunox --gas auto --gas-adjustment 1.5 -y -b block --chain-id testing --node http://localhost:26657/
Error: rpc error: code = InvalidArgument desc = out of gas in location: Compiling WASM Bytecode; gasWanted: 100000000, gasUsed: 308859461: out of gas: invalid request
```

**Comment by the-frey** [comment]
Mainnet gas limit, compile cost at `500`:

```
TX Flags: --gas-prices 0.01ujunox --gas auto --gas-adjustment 1.5 -y -b block --chain-id testing --node http://localhost:26657/
Error: rpc error: code = InvalidArgument desc = out of gas in location: 
Compiling WASM Bytecode; gasWanted: 100000000, gasUsed: 154897461: out of gas: invalid request
```

**Comment by the-frey** [comment]
OKAY those local testing amounts were on a node with NO MIN FEES SET in `app.toml`. Once set, it all gets a bit harder to calculate

**Comment by the-frey** [comment]
Okay with gas fees set to `0.025` we arrive closer to something that makes sense. With it set to 200:

0.1 price needed to work

```
TX Flags: --gas-prices 0.1ujunox --gas auto --gas-adjustment 1.5 -y -b block --chain-id testing --node http://localhost:26657/
gas estimate: 93793536
```

which is `9379354` in fees

**Pull request merged**
