### PR TITLE
fix: Ignoring error "validator is not a valid name or address…

### PR DESCRIPTION
**Pull request by deveusss**
This error is fixing error "validator is not a valid name or address: decoding bech32 failed: invalid separator index -1"
When error is thrown, script is unable to call "junod gentx" and "add-genesys-account" functions.
The brings validator into invalid state, and junod returns another error "rpc error: code = NotFound desc = account" while signing transactions.

### CODE REVIEW

**Comment by the-frey** [comment]
This is not an error. It's simply creating a validator if there isn't one. The reason you can't submit a gentx is because the chain is already started. 

If you want to submit a gentx ahead of time you should use a custom genesis file and pass it in. Ditto for the adding of a genesis balance. 

Though, it should be noted for the latter use-case that you can just pass in a different address to the default user and it will be provisioned.

i.e. the address at the end of commands such as those in 

https://docs.junonetwork.io/smart-contracts-and-junod-development/junod-local-dev-setup#run-juno

**Comment by deveusss** [comment]
> This is not an error. It's simply creating a validator if there isn't one. The reason you can't submit a gentx is because the chain is already started.
> 
> If you want to submit a gentx ahead of time you should use a custom genesis file and pass it in. Ditto for the adding of a genesis balance.
> 
> Though, it should be noted for the latter use-case that you can just pass in a different address to the default user and it will be provisioned.
> 
> i.e. the address at the end of commands such as those in
> 
> https://docs.junonetwork.io/smart-contracts-and-junod-development/junod-local-dev-setup#run-juno
--------------------------------------------
this command from docs is also not working for macos.
>This is not an error. It's simply creating a validator if there isn't one.

That the exact problem, it fails when checking for existence)

**Comment by the-frey** [comment]
I've just run this on my machine (mac) and can confirm it works.

```sh
docker run -it \
  --name juno_node_1 \
  -p 1317:1317 \
  -p 26656:26656 \
  -p 26657:26657 \
  -e STAKE_TOKEN=ujunox \
  -e UNSAFE_CORS=true \
  ghcr.io/cosmoscontracts/juno:v9.0.0 \
  ./setup_and_run.sh juno16g2rahf5846rxzp3fwlswy08fz8ccuwk03k57y
```

**Comment by the-frey** [comment]
Also confirmed working on MBP 2018 with Intel

**Comment by the-frey** [comment]
When you run 

```sh
docker run -it \
  --name juno_node_1 \
  -p 1317:1317 \
  -p 26656:26656 \
  -p 26657:26657 \
  -e STAKE_TOKEN=ujunox \
  -e UNSAFE_CORS=true \
  ghcr.io/cosmoscontracts/juno:v9.0.0 \
  ./setup_and_run.sh juno16g2rahf5846rxzp3fwlswy08fz8ccuwk03k57y
  ```
  
What is the error you see?

**Pull request closed without merging**
