### PR TITLE
Version Bumps + IBC v7.1.0 upgrade handler

### PR DESCRIPTION
**Pull request by Reecepbcups**

### CODE REVIEW

**Comment by Reecepbcups** [comment]
hmm IBC breakage from the 7 -> 7.1 bump without upgrade

odd, will dive more into. Did not see any app.go required changes in the changelog

**Comment by faddat** [comment]
I suspect it is interchain test and/or pfm having issues with 7.1 but I'm not certain of this.

**Comment by Reecepbcups** [comment]
> I suspect it is interchain test and/or pfm having issues with 7.1 but I'm not certain of this.
> 
> I'm at least certain when it comes to pfm:
> 
> https://github.com/cosmos/ibc-apps/blob/8252b32d8c1342145b559f7a7b654bb0a11c3a6f/modules/async-icq/go.mod#L21
> 
> It shouldn't under any circumstances import tendermint. Fixing and will post pr here.
> 
> [cosmos/ibc-apps#27](https://github.com/cosmos/ibc-apps/pull/27)

Having tendermint as an import is nothing even related to the issue / logs provided.

Issue with with rly, Justin has a fix here: https://github.com/cosmos/relayer/pull/1191. Once that PR is merged to main, this PR will be successful.

**Review by dimiandre — APPROVED** [review]
lgtm

**Comment by faddat** [comment]
@Reecepbcups ok, I will still assert that it's something that should never happen on 47....

**Review by faddat — APPROVED** [review]

**Pull request merged**
