### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by dimiandre**

### CODE REVIEW

**Comment by nullmames** [comment]
LGTM

**Comment by the-frey** [comment]
This is good, but I've been thinking for ages we should just bin loads of the stuff that's just not relevant. Only devs and validators read this page (post genesis) - have suggested a slightly edited and much cut-down version in #299

**Comment by faddat** [comment]
I think I prefer @the-frey more reductive approach.  Also want to add a state sync step, too.

**Comment by faddat** [comment]
I think I prefer @the-frey more reductive approach.  Also want to add a state sync step, too.

**Pull request closed without merging**
