### PR TITLE
Add test for msg server feeShare

### LINKED ISSUE #415: Tests for the FeeShare module
Following #412, we should add more tests for feeshare  module keeper.

### PR DESCRIPTION
**Pull request by GNaD13**
Close #415 
Add some test for feeshare module

### CODE REVIEW

**Review by faddat — APPROVED** [review]

**Comment by GNaD13** [comment]
This PR should merge after Oracle. These 2 branch have a conflit with test-helper.go

**Comment by faddat** [comment]
@GNaD13 hey, maybe it should merge before oracle?  We can work out the conflict afterwards.

@Reecepbcups / @JakeHartnell could you review?

**Comment by GNaD13** [comment]
> @GNaD13 hey, maybe it should merge before oracle?  We can work out the conflict afterwards.
> 
> @Reecepbcups / @JakeHartnell could you review?

Ok, I can fix conflict in Oracle later

**Review by faddat — APPROVED** [review]
this could be useful, since it seems like there is some kind of issue with feeShare (protos, maybe?)

**Comment by Reecepbcups** [comment]
@GNaD13 What is that `reflect.wasm` doing in testdata? doesn't seem like anything. So anything related to that should be removed then it LTGM

**Comment by GNaD13** [comment]
> @GNaD13 What is that `reflect.wasm` doing in testdata? doesn't seem like anything. So anything related to that should be removed then it LTGM

We use it to instantiate and setting up environment for testing

**Comment by Reecepbcups** [comment]
Ohh I see! Sorry I was thinking it was something totally unrelated 👍🏻

**Comment by Reecepbcups** [comment]
@GNaD13 Should we merge https://github.com/CosmosContracts/juno/pull/439 first, then this, then oracle?

**Comment by GNaD13** [comment]
> @GNaD13 Should we merge https://github.com/CosmosContracts/juno/pull/439 first, then this, then oracle?

I think it fine, but want to know some opinions from @vuong177

**Comment by faddat** [comment]
I think that we should get this merged ASAP.

**Review by Reecepbcups — APPROVED** [review]
We can merge the .proto changes after, then oracle after that. Thanks

**Pull request merged**
