### PR TITLE
Dang/add twap

### PR DESCRIPTION
**Pull request by faddat**
Making a PR for dang's twap work for the oracle.

### CODE REVIEW

**Comment by GNaD13** [comment]
> Making a PR for dang's twap work for the oracle.

thank you sir :3. Currently, We have some change in the price history logic. The detail is described here #443. The change may affect to TWAP, so I need to work on it first and will back to TWAP asap :3

**Comment by faddat** [comment]
I think that we should try to get the oracle merged, that way these PR's target main

**Comment by Reecepbcups** [comment]
@GNaD13 This can target main now (oracle merged)

**Comment by GNaD13** [comment]
> 

Oh, I forgot this PR, I think this PR can just easily close. Everythings already on Oracle. 

> > Making a PR for dang's twap work for the oracle.
> 
> thank you sir :3. Currently, We have some change in the price history logic. The detail is described here #443. The change may affect to TWAP, so I need to work on it first and will back to TWAP asap :3

As I said here, the new logic have been already implemented in Oracle. So this PR can just close

**Pull request closed without merging**
