### PR TITLE
old x/globalfee

### PR DESCRIPTION
**Pull request by Reecepbcups**
Pulled forward from Gaiav8 - SDK v45 for Juno v12
Merges wasmd 30 branch into here

Commonwealth: https://commonwealth.im/juno/discussion/8386-implement-xglobalfee

Feature:
```
- Sets a minimum fee for the entire network
- A Node can set a higher fee than the minimum, but not lower
- Validators can not accept anything which is not in the globalfee params
```

After upgrade, community can decide on good fees / denoms to accept (usdc, juno, osmo)

`junod tx gov submit-proposal param-change ~/Desktop/Work/paramChange.json --from $KEY --keyring-backend os --chain-id juno-1 --yes --broadcast-mode block`
```json
{
    "title": "MinimumGasPricesParam Change",
    "description": "add juno minimum fee",
    "changes": [
      {
        "subspace": "globalfee",
        "key": "MinimumGasPricesParam",
        "value": [{"denom":"ujuno","amount":"0.002500000000000000"}]
      }
    ],
    "deposit": "1000000ujuno"
}
```

### CODE REVIEW

**Comment by faddat** [comment]
Hey, this is very sensible!

I am going to put a post on commonwealth about it, but yep, bit +1 from me.

**Comment by faddat** [comment]
```log
go mod tidy
go: downloading github.com/cosmos/gaia/v8 v8.0.0-20221205165440-0901d27ed915
go: finding module for package github.com/strangelove-ventures/ibctest/v6/testutil
go: finding module for package github.com/strangelove-ventures/ibctest/v6/chain/cosmos
go: finding module for package github.com/strangelove-ventures/ibctest/v6
go: finding module for package github.com/icza/dyno
go: finding module for package github.com/strangelove-ventures/ibctest/v6/ibc
go: found github.com/icza/dyno in github.com/icza/dyno v0.0.0-20220812133438-f0b6f8a18845
go: found github.com/strangelove-ventures/ibctest/v6 in github.com/strangelove-ventures/ibctest/v6 v6.0.0-20221202162429-9359b061fbe5
go: found github.com/strangelove-ventures/ibctest/v6/chain/cosmos in github.com/strangelove-ventures/ibctest/v6 v6.0.0-20221202162429-9359b061fbe5
go: found github.com/strangelove-ventures/ibctest/v6/ibc in github.com/strangelove-ventures/ibctest/v6 v6.0.0-20221202162429-9359b061fbe5
go: found github.com/strangelove-ventures/ibctest/v6/testutil in github.com/strangelove-ventures/ibctest/v6 v6.0.0-20221202162429-9359b061fbe5
go: downloading github.com/ChainSafe/go-schnorrkel/1 v0.0.0-00010101000000-000000000000
go: downloading github.com/klauspost/cpuid v0.0.0-20170728055534-ae7887de9fa5
go: finding module for package github.com/cosmos/cosmos-sdk/x/auth/client/rest
go: finding module for package github.com/cosmos/cosmos-sdk/types/rest
go: finding module for package github.com/cosmos/cosmos-sdk/x/auth/legacy/legacytx
go: finding module for package github.com/cosmos/cosmos-sdk/client/rest
go: finding module for package github.com/cosmos/cosmos-sdk/x/gov/client/rest
go: finding module for package google.golang.org/grpc/credentials/insecure
github.com/CosmosContracts/juno/v12/app imports
	github.com/cosmos/cosmos-sdk/x/auth/client/rest: module github.com/cosmos/cosmos-sdk@latest found (v0.46.6), but does not contain package github.com/cosmos/cosmos-sdk/x/auth/client/rest
github.com/CosmosContracts/juno/v12/x/mint/client/rest imports
	github.com/cosmos/cosmos-sdk/client/rest: module github.com/cosmos/cosmos-sdk@latest found (v0.46.6), but does not contain package github.com/cosmos/cosmos-sdk/client/rest
github.com/CosmosContracts/juno/v12/x/mint/client/rest imports
	github.com/cosmos/cosmos-sdk/types/rest: module github.com/cosmos/cosmos-sdk@latest found (v0.46.6), but does not contain package github.com/cosmos/cosmos-sdk/types/rest
github.com/CosmosContracts/juno/v12/app imports
	github.com/cosmos/gaia/v8/app/params imports
	github.com/cosmos/cosmos-sdk/x/auth/legacy/legacytx: module github.com/cosmos/cosmos-sdk@latest found (v0.46.6), but does not contain package github.com/cosmos/cosmos-sdk/x/auth/legacy/legacytx
github.com/CosmosContracts/juno/v12/app imports
	github.com/cosmos/ibc-go/v3/modules/core/02-client/client imports
	github.com/cosmos/cosmos-sdk/x/gov/client/rest: module github.com/cosmos/cosmos-sdk@latest found (v0.46.6), but does not contain package github.com/cosmos/cosmos-sdk/x/gov/client/rest
github.com/CosmosContracts/juno/v12/cmd/junod imports
	github.com/cosmos/cosmos-sdk/server imports
	google.golang.org/grpc/credentials/insecure: module google.golang.org/grpc@latest found (v1.51.0, replaced by google.golang.org/grpc@v1.33.2), but does not contain package google.golang.org/grpc/credentials/insecure
github.com/CosmosContracts/juno/v12/ibctest tested by
	github.com/CosmosContracts/juno/v12/ibctest.test imports
	github.com/strangelove-ventures/ibctest/v6 imports
	github.com/strangelove-ventures/ibctest/v6/chain/polkadot imports
	github.com/ChainSafe/go-schnorrkel/1: github.com/ChainSafe/go-schnorrkel/1@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```

**Comment by Reecepbcups** [comment]
No clue why that Gov Contract fails given globalfee doesn't touch anything with that and passed before
My thought is NewGovPreventSpamDecorator, but that passes in main so.... weird, trying to see how I can test locally with `act` or something

**Comment by faddat** [comment]
heh, so, ended up in approximately the same spot.  On my end the "hints" did involve gas errors.

Good luck sir!

**Comment by the-frey** [comment]
`NewGovPreventSpamDecorator` has def been tested against that CI workflow? AFAICR any decorator that affects the endblocker _could_ have the chance of borking the sudo endpoint in certain situations. 

Only other thought - wasm gas depends on its own ante decorator, so there might be some interaction between the two?

**Comment by the-frey** [comment]
So if the latter case is related... might be an ordering thing.

**Comment by Reecepbcups** [comment]
@the-frey I just ran this locally with no issue (non docker instance though) for upload, gov proposal, and execute withdraw all being successful on the globalfee latest build. So this may be an issue with the deploy script itself in that repo for 0.3.4-alpha?

Here is my bash script
https://gist.github.com/Reecepbcups/39cae4ac45ebfb93db9d19bbb6336688

So the branch is good, test is bad it seems - I'll look into it more later

**Review by faddat — DISMISSED** [review]

**Comment by faddat** [comment]
reece, if we set --gas auto or maybe --fees auto this might make it pass - I will have a go...

**Comment by faddat** [comment]
@Reecepbcups I think it is here:

https://github.com/CosmosContracts/cw-unity-prop/blob/main/scripts/deploy_ci.sh

**Comment by Reecepbcups** [comment]
> @Reecepbcups I think it is here:
> 
> https://github.com/CosmosContracts/cw-unity-prop/blob/main/scripts/deploy_ci.sh
> 
> Specifically:
> 
> https://github.com/CosmosContracts/cw-unity-prop/blob/5db1d23986ce08632b6105860aea2f9538555075/scripts/deploy_ci.sh#L44

Huh? No this is the test / liune failing in the above, it has to do with the actual sudo upgrade, the contract uploads / creates an instance just fine
https://github.com/CosmosContracts/cw-unity-prop/blob/5db1d23986ce08632b6105860aea2f9538555075/scripts/submit_gov_ci.sh#L72

**Comment by Reecepbcups** [comment]
Even when I remove the globalfee ante handler it fails @faddat / @the-frey  AHHHHH
my head is done in. Going to see if I can make a fresh PR now and have it pass sigh

**Pull request closed without merging**
