### PR TITLE
Update go.mod

### PR DESCRIPTION
**Pull request by faddat**
Bump back down to go 1.18

### CODE REVIEW

**Review by the-frey — APPROVED** [review]
Downgraded the dockerfile as well and resolved the errors with superlinter.

**Comment by faddat** [comment]
Personally I would not have downgraded the docker file but no big deal.

I think that we actually want to build using 19, because that's what most developers are going to be using and stuff like that but we can just bump down the required go version.

I should also probably make us our own build container there's really no reason to use anyone else's and well I'll see what I can do with that.

**Comment by the-frey** [comment]
Well, the docker container should just use the same version as the go mod (if there's a strong disagreement, then it's easy to change that). Kind of disagree about our own build container, base image plus some steps is... kind of fine tbh?

**Comment by faddat** [comment]
Oh no it's not as strong disagreement at all I think we're all good, I was maybe just musing

**Comment by the-frey** [comment]
Cool, let's 🚢 this one then?

**Comment by faddat** [comment]
oh definitely!

**Comment by dimiandre** [comment]
lgtm

**Review by dimiandre — APPROVED** [review]

**Pull request merged**
