### PR TITLE
feat(scripts) - Relay CW20 between localnets example

### PR DESCRIPTION
**Pull request by Reecepbcups**
Relays a CW20 with the CW20_ICS20 contract. Tested locally, and tested with mainnet no issues (hermes)

image

### CODE REVIEW

**Comment by the-frey** [comment]
This looks really good

**Comment by the-frey** [comment]
My additional thought is that @Reecepbcups has contributed so many useful bash scripts, at some point we should catalogue them better. Whether that's in their own repo or in some way within this one so they're clearly identified &/or thus re-usable to even other chains, since it's all good work

**Comment by the-frey** [comment]
Sounds great 👍

**Comment by faddat** [comment]
Reece, thanks a ton for checking into this in detail. 

Generally, still happy about monorepos, and prefer things to target this repository

**Comment by faddat** [comment]
Just so you know I think this actually should be merged. It's really valuable documentation and thank you for making it.

**Comment by Reecepbcups** [comment]
@faddat I agree, I just need to spend time to clean it up & add CW721 examples, Ill get back to it this weekend most likely

**Review by faddat — APPROVED** [review]
very approve, and very like that it is here in the main repository directly.

**Review by JakeHartnell — APPROVED** [review]

**Pull request merged**
