### PR TITLE
Change contract CI to be inside this repo

### PR DESCRIPTION
**Pull request by anhductn2001**
This PR resolved issue https://github.com/CosmosContracts/juno/issues/288
Code is compiled elsewhere and bring the wasm binaries straight inside this repo.

### CODE REVIEW

**Comment by faddat** [comment]
Thank you so much for this contribution

**Comment by anhductn2001** [comment]
Sorry, I realize there is some problem with the file binary .wasm and I will fix it in the next PR

**Comment by anhductn2001** [comment]
I have successfully run test on local environment but when running on github action has error: Connection refuse, I will continue to fix it

**Comment by anhductn2001** [comment]
i found the cause of the error. It's the docker-compose up is not finished yet

**Comment by the-frey** [comment]
Hi, probably don't do any more work on this right now. 
I was going to pick up this issue next week and I have some thoughts about how to improve it.

**Pull request closed without merging**
