### PR TITLE
fix! not loading in contracts with custom WasmVM after upgrade

### PR DESCRIPTION
**Pull request by Reecepbcups**
ref PR #960 for further information and debugging scripts

Will need to backport to main

- Tag as v19.2? (or v20 since it is state breaking, just with the v19 namespace)
- need to try on testnet
- Need to halt and patch to mainnet vals

### CODE REVIEW

**Comment by Reecepbcups** [comment]
@dimiandre I'm fine with that. Didn't know if Core-1 could get the votes. 

The first commit in this PR is from the release/v19 branch. So I can't remove that but will get the handler out if desired

**Comment by Reecepbcups** [comment]
lets do the halt and patch

**Comment by Reecepbcups** [comment]
Can confirm v18 -> this branch works as expected with it.
image

**Review by dimiandre — APPROVED** [review]
looks good

**Pull request merged**
