### PR TITLE
bump to v11

### PR DESCRIPTION
**Pull request by vuong177**
Change import paths to v11

### CODE REVIEW

**Comment by faddat** [comment]
@vuong177 to keep this PR small, I changed the description for it to match what it currently does. 

Nice work!

**Comment by faddat** [comment]
hey uh, im sorry, I accidentally edited your reply.

**Review by faddat — APPROVED** [review]

**Comment by the-frey** [comment]
I think main can now be merged into this. Superlinter is disabled on main, and then there's an upgrades folder with a draft handler for v11 (wasmd has a couple changes that need adding to ICA) - so that handler can just be called.

**Comment by faddat** [comment]
@the-frey I reckon we can close this now?  I just merged these changes in the form of #313

**Pull request closed without merging**
