### PR TITLE
[v15] test: FeeShare interchain test

### PR DESCRIPTION
**Pull request by Reecepbcups**
(Merges tokenfactory PR in first since that has my latest TF features in the correct location)

## Features
- Adds interchain test for feeshare
- Speeds up per PR test time

## File(s) of importance
- interchaintest/module_feeshare_test.go https://github.com/CosmosContracts/juno/pull/668/commits/c05d38050cb834a99970226399480f2d9536e4b5
- .github/workflows/test-simulation.yml https://github.com/CosmosContracts/juno/pull/668/commits/ef9b2062f88d0a6921b1a01cd94671c097e192ae (Only need to full sim on merge to main. Other test fail before this does)

### CODE REVIEW

**Review by faddat — APPROVED** [review]

**Comment by faddat** [comment]
* https://github.com/CosmosContracts/juno/issues/674

**Comment by dimiandre** [comment]
Automatic merge of the other PR created some conflicts here.

**Review by dimiandre — APPROVED** [review]
That's super useful! Also can't wait to see some more documentation around interchain test

**Comment by Reecepbcups** [comment]
Thanks fixing

**Pull request merged**
